// clientes/livros-react/src/componentes/LivroDados.js
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import ControleLivros from '../controle/ControleLivros';
import ControleEditora from '../controle/ControleEditora';

const LivroDados = () => {
    const controleLivro = new ControleLivros();
    const controleEditora = new ControleEditora();
    const opcoes = controleEditora.getEditoras().map((editora) => ({
        value: editora.codEditora,
        text: editora.nome,
    }));

    const [titulo, setTitulo] = useState('');
    const [resumo, setResumo] = useState('');
    const [autores, setAutores] = useState('');
    const [codEditora, setCodEditora] = useState(opcoes.length > 0 ? opcoes[0].value : 0);
    const navigate = useNavigate();

    const tratarCombo = (event) => {
        setCodEditora(Number(event.target.value));
    };

    const incluir = (event) => {
        event.preventDefault();

        const livro = {
            codigo: '',
            codEditora,
            titulo,
            resumo,
            autores: autores.split('\n'),
        };

        controleLivro
            .incluir(livro)
            .then(() => navigate('/'))
            .catch((error) => console.error('Erro ao incluir livro:', error));
    };

    return (
        <main className="container mt-5">
            <h1>Dados do Livro</h1>
            <form onSubmit={incluir}>
                <div className="mb-3">
                    <label htmlFor="titulo" className="form-label">Título</label>
                    <input
                        type="text"
                        id="titulo"
                        className="form-control"
                        value={titulo}
                        onChange={(e) => setTitulo(e.target.value)}
                        required
                    />
                </div>
                <div className="mb-3">
                    <label htmlFor="resumo" className="form-label">Resumo</label>
                    <textarea
                        id="resumo"
                        className="form-control"
                        value={resumo}
                        onChange={(e) => setResumo(e.target.value)}
                        required
                    />
                </div>
                <div className="mb-4">
                    <label htmlFor="codEditora" className="form-label">Editora</label>
                    <select
                        id="codEditora"
                        className="form-select"
                        value={codEditora}
                        onChange={tratarCombo}
                        required
                    >
                        {opcoes.map((opcao) => (
                            <option key={opcao.value} value={opcao.value}>
                                {opcao.text}
                            </option>
                        ))}
                    </select>
                </div>
                <div className="mb-4">
                    <label htmlFor="autores" className="form-label">Autores (1 por linha)</label>
                    <textarea
                        id="autores"
                        className="form-control"
                        value={autores}
                        onChange={(e) => setAutores(e.target.value)}
                        required
                    />
                </div>

                <button type="submit" className="btn btn-primary">Salvar Dados</button>
            </form>
        </main>
    );
};

export default LivroDados;

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro = new Livro('', 0, '', '', []);
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir(): void {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.incluir(this.livro).then((sucesso) => {
      if (sucesso) {
        this.router.navigateByUrl('/lista');
      } else {
        alert('Erro ao incluir o livro. Tente novamente.');
      }
    }).catch((erro) => {
      console.error('Erro ao incluir o livro:', erro);
      alert('Erro ao incluir o livro. Tente novamente.');
    });
  }
}

<main class="container mt-5">
  <h1 class="mb-4">Cadastro de Livro</h1>
  <form (submit)="incluir()" ngNativeValidate>
    <div class="form-group">
      <label for="titulo">Título</label>
      <input
        type="text"
        class="form-control"
        id="titulo"
        required
        [(ngModel)]="livro.titulo"
        name="titulo"
      />
    </div>
    <div class="form-group">
      <label for="resumo">Resumo</label>
      <textarea
        class="form-control"
        id="resumo"
        required
        [(ngModel)]="livro.resumo"
        name="resumo"
      ></textarea>
    </div>
    <div class="form-group">
      <label for="codEditora">Editora</label>
      <select
        class="form-control"
        id="codEditora"
        required
        [(ngModel)]="livro.codEditora"
        name="codEditora"
      >
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">
          {{ editora.nome }}
        </option>
      </select>
    </div>
    <div class="form-group">
      <label for="autores">Autores (um por linha)</label>
      <textarea
        class="form-control"
        id="autores"
        required
        [(ngModel)]="autoresForm"
        name="autores"
      ></textarea>
    </div>
    <button
      type="submit"
      class="btn btn-primary"
    >
      Cadastrar
    </button>
  </form>
</main>
