// clientes/livros-react/src/App.tsx
import { BrowserRouter as Router, Routes, Route, Link } from 'react-router-dom';
import LivroLista from './componentes/LivroLista';
import LivroDados from './componentes/LivroDados';

const App = () => {
  return (
    <Router>
        <nav className="navbar navbar-expand-lg navbar-light bg-light">
            <div className="container-fluid">
                <Link className="navbar-brand" to="/">Catálogo de Livros</Link>
                <div className="collapse navbar-collapse">
                    <ul className="navbar-nav">
                        <li className="nav-item">
                            <Link className="nav-link" to="/">Lista de Livros</Link>
                        </li>
                        <li className="nav-item">
                            <Link className="nav-link" to="/dados">Cadastro de Livro</Link>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <main>
            <Routes>
                <Route path="/" element={<LivroLista />} />
                <Route path="/dados" element={<LivroDados />} />
            </Routes>
        </main>
    </Router>
);
};

export default App;

// clientes/livros-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { LivroListaComponent } from './livro-lista/livro-lista.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, CommonModule, RouterModule, LivroListaComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'livros-angular';
}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" routerLink="#">Livros Angular</a>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" routerLink="/lista">Lista de Livros</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" routerLink="/dados">Cadastro de Livro</a>
      </li>
    </ul>
  </div>
</nav>
<div class="container mt-3">
  <router-outlet></router-outlet>
  <!-- <app-livro-lista></app-livro-lista> -->
</div>
