// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
// import { Component, OnInit } from '@angular/core';
// import { CommonModule } from '@angular/common';
// import { RouterModule } from '@angular/router';
// import { Editora } from '../editora';
// import { Livro } from '../livro';
// import { ControleEditoraService } from '../controle-editora.service';
// import { ControleLivrosService } from '../controle-livros.service';

// @Component({
//   selector: 'app-livro-lista',
//   standalone: true,
//   imports: [CommonModule, RouterModule],
//   templateUrl: './livro-lista.component.html',
//   styleUrls: ['./livro-lista.component.css']
// })
// export class LivroListaComponent implements OnInit {
//   public editoras: Array<Editora> = [];
//   public livros: Array<Livro> = [];

//   constructor(
//     private servEditora: ControleEditoraService,
//     private servLivros: ControleLivrosService
//   ) {}

//   ngOnInit(): void {
//     this.editoras = this.servEditora.getEditoras();
//     this.livros = this.servLivros.obterLivros();
//   }

//   excluir = (codigo: number): void => {
//     this.servLivros.excluir(codigo);
//     this.livros = this.servLivros.obterLivros();
//   };

//   obterNome = (codEditora: number): string | undefined => {
//     return this.servEditora.getNomeEditoras(codEditora);
//   };
// }



import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) {}

  async ngOnInit(): Promise<void> {
    this.editoras = this.servEditora.getEditoras();
    this.livros = await this.servLivros.obterLivros();
  }

  excluir = async (codigo: string): Promise<void> => {
    const sucesso = await this.servLivros.excluir(codigo);
    if (sucesso) {
      this.livros = await this.servLivros.obterLivros();
    } else {
      alert('Erro ao excluir o livro. Tente novamente.');
    }
  };

  obterNome = (codEditora: number): string | undefined => {
    return this.servEditora.getNomeEditoras(codEditora);
  };
}

<main class="container mt-5">
  <h1 class="mb-4">Lista de Livros</h1>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Título</th>
        <th>Editora</th>
        <th>Autores</th> 
        <th></th>       
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros">
        <td>
          {{ livro.titulo }}          
        </td>
        <td>{{ obterNome(livro.codEditora) }}</td>
        <td>
          <ul>
            <li *ngFor="let autor of livro.autores">{{ autor }}</li>
          </ul>
        </td>
        <td>
          <button class="btn btn-danger btn-sm ml-2" (click)="excluir(livro.codigo)">
            Excluir
          </button>
        </td>
      </tr>
    </tbody>
  </table>
</main>

// clientes/livros-react/src/componentes/LivroLista.js
import { useEffect, useState } from 'react';
import ControleLivros from '../controle/ControleLivros';
import ControleEditora from '../controle/ControleEditora';
import '../../src/index.css';

const controleLivro = new ControleLivros();
const controleEditora = new ControleEditora();

const LinhaLivro = ({ livro, excluir }) => {
    const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);

    return (
        <tr className="table-lista-livros">
            <td>{livro.codigo}</td>
            <td>{livro.titulo}</td>
            <td>{livro.resumo}</td>
            <td>
                <ul className="list-unstyled">
                    {livro.autores.map((autor, index) => (
                        <li key={index}>{autor}</li>
                    ))}
                </ul>
            </td>
            <td>{nomeEditora}</td>
            <td>
                <button
                    className="btn btn-danger"
                    onClick={() => excluir(livro.codigo)}
                >
                    Excluir
                </button>
            </td>
        </tr>
    );
};

const LivroLista = () => {
    const [livros, setLivros] = useState([]);
    const [carregado, setCarregado] = useState(false);

    useEffect(() => {
        const fetchLivros = async () => {
            controleLivro
                .obterLivros()
                .then((dados) => {
                    setLivros(dados);
                    setCarregado(true);
                })
                .catch((error) => console.error("Erro ao carregar livros:", error));
        };

        if (!carregado) {
            fetchLivros();
        }
    }, [carregado]);

    const excluir = (codigo) => {
        controleLivro
            .excluir(codigo)
            .then(() => {
                setCarregado(false);
            })
            .catch((error) => console.error("Erro ao excluir livro:", error));
    };

    return (
        <main className="container mt-4">
            <h1 className="mb-4">Catálogo de Livros</h1>
            <table className="table table-striped">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th className="col-titulo">Título</th>
                        <th>Resumo</th>
                        <th className="col-autores">Autores</th>
                        <th className="col-editora">Editora</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {livros.map((livro, index) => (
                        <LinhaLivro key={index} livro={livro} excluir={excluir} />
                    ))}
                </tbody>
            </table>
        </main>
    );
};

export default LivroLista;
